version: '3'
services:
  web:
    image: 'nginx:alpine'
    ports:
      - '3035:80'
    volumes:
      - './:/var/www/'
      - './site.conf:/etc/nginx/conf.d/default.conf'
    links:
      - 'php'
  php:
    image: 'php:7.4-fpm-alpine'
    volumes:
      - './:/var/www/'
    working_dir: '/var/www'
